# Generated by Django 5.2.3 on 2025-07-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketresponse',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='responder',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketResponse',
        ),
    ]
